### ISSUE TITLE
Make website responsive.

### ISSUE THREAD

**Issue by zeel-codder** [zeel-codder/Recursion-Hub#24]

**Comment by fastboot** [comment]
What exactly do you mean by making it responsive?

**Comment by ayushgoswamiabr** [comment]
I have Made the Website Responsive and opened a Pull Request #25 Please Review

**Comment by zeel-codder** [comment]
@fastboot  mobile or diff" divice view must be same and nice.

**Comment by Bhawna147** [comment]
@zeel-codder please assign this issue to me
