### ISSUE TITLE
Would like to upgrade ui !

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [zeel-codder/Recursion-Hub#97]
Hey @zeel-codder ,
I would like to update the whole ui of this project so that it could look responsive as you can see it's not a11y website

thanks,
ShGI

**Comment by zeel-codder** [comment]
go ahed

**Comment by SGI-CAPP-AT2** [comment]
@zeel-codder 
This issue is solved with #98 PR

Thanks,
ShGI
